### ISSUE TITLE
`createMuiTheme` import failure with material-ui ^v4.12

### ISSUE THREAD

**Issue by mdlavin** [lifeomic/chroma-react#176]
It looks like in the v4.12 release, they renamed the module failure and it causes webpack errors at dev time

The problematic change
https://github.com/mui-org/material-ui/commit/bf65be2e27039f3cf9084577d0a8b7bc772bc52c

The failure during webpack with v4.12
`node_modules/@material-ui/core/styles/createMuiTheme.ts doesn't exist`

**Comment by mdlavin** [comment]
it can be worked around by adding the following resolution:

```
  "resolutions": {
    "@material-ui/core": "~4.11" 
  }
```

**Comment by ynotdraw** [comment]
Excellent find @mdlavin, glad you found a workaround for the time being.  Chroma is long overdue for some dependency upgrades.  Thanks for posting the material-ui diff as well!
