### ISSUE TITLE
Proposal: Add Date Picker component

### ISSUE THREAD

**Issue by ynotdraw** [lifeomic/chroma-react#202]
Having built-in date picker components would be extremely helpful.  Probably need to work with design to figure out our use cases and how it should look/work from a UI/UX perspective

**Comment by smolster** [comment]
Going to start work on a "day picker". Internal Slack thread: https://lifeomic.slack.com/archives/CHMFL4PQT/p1636041527012400

**Comment by smolster** [comment]
I added a `DayPicker` in #215. I'm going to leave this open for now, while our design team works on a UI for time selection.

Once that's done, I'll update `DayPicker` or maybe create a new `DatePicker` link that PR to this issue.

**Comment by ynotdraw** [comment]
(Closing out old issues I've filed to clean up my GitHub issues tab!)
