### ISSUE TITLE
Proposal: Re-evaluate Modal component props

### ISSUE THREAD

**Issue by ynotdraw** [lifeomic/chroma-react#204]
We should re-evaluate the Modal component props.  In particular, `size` and `fullWidth` are extremely confusing.  We have some feedback on this on https://github.com/lifeomic/chroma-react/pull/116#issuecomment-822731493.  What would be nice is if we have a new `height` and `width` props, with four different size options for each, allowing a bit deeper customization.

We can make this a breaking change if it makes sense, or provide new props and deprecate the old ones.  We could even look at replacing the underpinnings with another library that may help us out a bit too 👍

**Comment by HaleyWardo** [comment]
Ticket created - [CHROM-196](https://lifeomic.atlassian.net/browse/CHROM-196)
